using System.Security.Cryptography;
using System.Text;
using System.Text.Json;

namespace JeetScreenRecorder.Licensing;

/// <summary>
/// Verifies the RSA-SHA256 signature that the server attaches to every
/// license/trial answer.  The PUBLIC key is embedded in the binary;
/// the private key never leaves the server.
///
/// Verification guarantees:
///   1. The response really came from our server (signed with the private key).
///   2. It was issued for THIS device (device_id inside the signed JSON matches).
///   3. It was a fresh response (nonce inside the signed JSON matches what we sent).
/// </summary>
internal static class SignatureVerifier
{
    // RSA-2048 PUBLIC key generated by the license server (tools/generate_keys.php).
    private const string PublicKeyPem =
        "-----BEGIN PUBLIC KEY-----\n" +
        "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAlOnIzKwq7DrUheFNeqSv\n" +
        "S92jJx8hgOGGcnzbmo+Ec9QVtwOGUSCfRErbhjxCQUeXoCGX3vzCUA/TOecARS//\n" +
        "983r57ZIW0x7u1jXapmEtDjsRtTxvWRzmKBwpe/AG8FoZ0+lZps3IO1TtxJbkKVm\n" +
        "5Rr2PtE8t9An/ZqR+CBS562bLC9VADDt/av+3B4nOkw54z+/74KUkHv1HD6ciHZe\n" +
        "m96FlSR0qCllD8Mg6Fx6ImSFvn0lvJKPAUGpZ/lN8wGsr1ia1uaFZLoMzMeNs1wU\n" +
        "sLTED0TdJ7vhDx4ii/Bjg37ReXl8a0SW7MIZtg+fsyQTcoPlS+DAyE2FVLWjUTzC\n" +
        "vwIDAQAB\n" +
        "-----END PUBLIC KEY-----";

    // -----------------------------------------------------------------------

    /// <summary>
    /// Verify the signed JSON blob + base64 signature returned by the server.
    /// Returns the inner payload dictionary, or throws if verification fails.
    /// </summary>
    public static Dictionary<string, JsonElement> VerifyAndParse(
        string signedJson,
        string signatureBase64,
        string expectedNonce,
        string expectedDeviceId)
    {
        // 1. Check RSA signature
        if (!RsaVerify(signedJson, signatureBase64))
            throw new LicenseException("Server response signature is invalid.");

        // 2. Parse inner JSON
        var doc = JsonSerializer.Deserialize<Dictionary<string, JsonElement>>(signedJson)
                  ?? throw new LicenseException("Server response payload is empty.");

        // 3. Nonce check (replay protection)
        if (!doc.TryGetValue("nonce", out var nonceEl) || nonceEl.GetString() != expectedNonce)
            throw new LicenseException("Server response nonce mismatch.");

        // 4. Device-id check (response is tied to this PC)
        if (!doc.TryGetValue("device_id", out var devEl) || devEl.GetString() != expectedDeviceId)
            throw new LicenseException("Server response device mismatch.");

        return doc;
    }

    // -----------------------------------------------------------------------

    private static bool RsaVerify(string data, string signatureBase64)
    {
        try
        {
            var sig = Convert.FromBase64String(signatureBase64);
            var dataBytes = Encoding.UTF8.GetBytes(data);

            using var rsa = RSA.Create();
            rsa.ImportFromPem(PublicKeyPem.AsSpan());
            return rsa.VerifyData(dataBytes, sig, HashAlgorithmName.SHA256, RSASignaturePadding.Pkcs1);
        }
        catch
        {
            return false;
        }
    }
}

/// <summary>Thrown when the license server returns an error or verification fails.</summary>
internal sealed class LicenseException : Exception
{
    /// <summary>HTTP status of the server reply (0 = no reply, e.g. network error).</summary>
    public int HttpStatus { get; }

    public LicenseException(string message) : base(message) { }
    /// <summary>True if the server's reply body was valid JSON (i.e. our license app answered, not a firewall/host error page).</summary>
    public bool IsJsonReply { get; }

    public LicenseException(string message, int httpStatus, bool isJsonReply = false) : base(message)
    {
        HttpStatus = httpStatus;
        IsJsonReply = isJsonReply;
    }
    public LicenseException(string message, Exception inner) : base(message, inner) { }

    /// <summary>
    /// True when the server answered and refused (blocked / forbidden / gone), as opposed to a
    /// network problem or a server crash. Used to lock a blocked trial instead of calling it "no internet".
    /// </summary>
    public bool IsServerRefusal =>
        IsJsonReply &&   // an HTML 403 from the web host / firewall must NOT lock the trial
        (HttpStatus is 401 or 402 or 403 or 410 or 423 ||
         (HttpStatus != 0 && (Message.Contains("block",    StringComparison.OrdinalIgnoreCase) ||
                              Message.Contains("expired",  StringComparison.OrdinalIgnoreCase) ||
                              Message.Contains("disabled", StringComparison.OrdinalIgnoreCase))));
}
