<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>JeetScreenRecorder</AssemblyName>
    <RootNamespace>JeetScreenRecorder</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Version>0.2.0</Version>
    <ApplicationIcon>Assets\JeetScreenRecorder.ico</ApplicationIcon>
    <Company>Amarjeet K Gupta</Company>
    <Product>Jeet Screen Recorder</Product>
  </PropertyGroup>
  <ItemGroup>
    <Resource Include="Assets\JeetScreenRecorder.ico" />
    <Resource Include="Assets\logo.png" />
    <Resource Include="Assets\logo256.png" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="System.IO" />
    <Using Include="System.Threading" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.1" />
    <PackageReference Include="NAudio" Version="2.2.1" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="8.0.0" />
  </ItemGroup>
</Project>
